import data.Person;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Person p = Person.newBuilder()
        .setAge(10)
        .setName("koyanagi")
        .build();
        System.out.println(p);
    }
}
